name: NPM Release

on:
    push:
        tags:
        - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get tag
              id: tag
              uses: dawidd6/action-get-tag@v1

            - name: npm install
              run: npm install

            - name: npm publish
              run: npm publish
              env:
                NPM_TOKEN: {{ secrets.NPM_TOKEN }}
